const data = [
	{
		network: "MTN",
		category: "Daily",
		price: "100.00",
		allowance: "100MB",
		product_id: "MT1",
		validity: "1 Day",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "200.00",
		allowance: "200MB",
		product_id: "MT2",
		validity: "3 Day",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1200.00",
		allowance: "1.5GB+2.4GB YouTube Night+3hr-200MB-YouTube Weekly",
		product_id: "MT251",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1000.00",
		allowance: "1.2GB Monthly Plan + FREE 2GB for YouTube and 200M",
		product_id: "MT208",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1600.00",
		allowance: "3GB+2GB YouTube Night+200MB YouTube Music + 5mins.",
		product_id: "MN3",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Yearly",
		price: "100000.00",
		allowance: "1TB",
		product_id: "MN4",
		validity: "365Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "250000.00",
		allowance: "1TB",
		product_id: "MN5",
		validity: "90 Days",
	},
	{
		network: "MTN",
		category: "Yearly",
		price: "450000.00",
		allowance: "4.5TB",
		product_id: "MN6",
		validity: "365 Days",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "600.00",
		allowance: "2.5GB 2-Day Plan",
		product_id: "MN8",
		validity: "2 Days",
	},
	{
		network: "MTN",
		category: "Yearly",
		price: "250000.00",
		allowance: "2.5TB",
		product_id: "MN9",
		validity: "365 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "20000.00",
		allowance: "100GB",
		product_id: "MM1",
		validity: "60 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "30000.00",
		allowance: "160GB",
		product_id: "MM2",
		validity: "60 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "50000.00",
		allowance: "400GB",
		product_id: "MM3",
		validity: "90 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "75000.00",
		allowance: "600GB",
		product_id: "MM4",
		validity: "90 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "6500.00",
		allowance: "25GB+2GB YouTube Night + 25mins.",
		product_id: "MM5",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "500.00",
		allowance: "750MB",
		product_id: "MM6",
		validity: "14 Days",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "1500.00",
		allowance: "5GB",
		product_id: "MM7",
		validity: "7 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "3000.00",
		allowance: "6GB+2GB YouTube Night+200MB YouTube Music + 15mins",
		product_id: "MM8",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "3500.00",
		allowance: "10GB+2GB YouTube Night+300MB YouTube Music + 20min",
		product_id: "MM9",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "22000.00",
		allowance: "120GB Monthly Plan + 80mins.",
		product_id: "MB1",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "10000.00",
		allowance: "25GB",
		product_id: "MB2",
		validity: "SME Data",
	},
	{
		network: "MTN",
		category: "2 Months",
		price: "50000.00",
		allowance: "165GB",
		product_id: "MB3",
		validity: "SME Data",
	},
	{
		network: "MTN",
		category: "3 Months",
		price: "100000.00",
		allowance: "360GB",
		product_id: "MB4",
		validity: "SME Data",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "2000.00",
		allowance: "4GB+2GB YouTube Night+200MB YouTube Music + 10mins",
		product_id: "MB5",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "4000.00",
		allowance: "12GB+2GB YouTube Night + 25mins.",
		product_id: "MD4",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "5500.00",
		allowance: "20GB+2GB YouTube Night+300MB YouTube Music + 25min",
		product_id: "MD1",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "11000.00",
		allowance: "40GB Monthly Plan + 40mins.",
		product_id: "MD2",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "16000.00",
		allowance: "75GB + 40mins",
		product_id: "MD3",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "50.00",
		allowance: "50MB",
		product_id: "MT001",
		validity: "24 hrs",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "150.00",
		allowance: "150MB",
		product_id: "MT002",
		validity: "30 days",
	},
	{
		network: "MTN",
		category: "DAILY",
		price: "350.00",
		allowance: "Data 1GB",
		product_id: "MT004",
		validity: "1GB Daily Plan + 3mins.",
	},
	{
		network: "MTN",
		category: "WEEKLY",
		price: "600.00",
		allowance: "1GB Weekly Plan + FREE 1GB for YouTube and 100MB f",
		product_id: "MT005",
		validity: "7 Days (MTN)",
	},
	{
		network: "MTN",
		category: "WEEKLY",
		price: "2000.00",
		allowance: "7GB",
		product_id: "MT008",
		validity: "7 DAYS",
	},
	{
		network: "MTN",
		category: "Xtradata 1000",
		price: "1000.00",
		allowance: "Xtradata 1000",
		product_id: "MT112",
		validity: "1000",
	},
	{
		network: "MTN",
		category: "Xtradata 2000",
		price: "2000.00",
		allowance: "Xtradata 2000",
		product_id: "MT113",
		validity: "2000",
	},
	{
		network: "MTN",
		category: "Xtradata 5000",
		price: "5000.00",
		allowance: "Xtradata 5000",
		product_id: "MT115",
		validity: "Xtradata 5000",
	},
	{
		network: "MTN",
		category: "Xtradata 10000",
		price: "10000.00",
		allowance: "Xtradata 10000",
		product_id: "MT116",
		validity: "Xtradata 10000",
	},
	{
		network: "MTN",
		category: "Xtradata 15000",
		price: "15000.00",
		allowance: "Xtradata 15000",
		product_id: "MT119",
		validity: "Xtradata 15000",
	},
	{
		network: "MTN",
		category: "Xtradata 20000",
		price: "20000.00",
		allowance: "Xtradata 20000",
		product_id: "MT109",
		validity: "Xtradata 20000",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "350.00",
		allowance: "1GB Daily Plan + 3mins.",
		product_id: "MT204",
		validity: "1 Day",
	},
	{
		network: "MTN",
		category: "MTN",
		price: "800.00",
		allowance: "3GB",
		product_id: "MT330",
		validity: "2 Days",
	},
	{
		network: "MTN",
		category: "Xtratalk 200",
		price: "200.00",
		allowance: "1000 voice & 20MB Data",
		product_id: "MT350",
		validity: "3 Day",
	},
	{
		network: "MTN",
		category: "Xtradata 200",
		price: "200.00",
		allowance: "N200 Voice & 400MB",
		product_id: "MT351",
		validity: "3 Day",
	},
	{
		network: "MTN",
		category: "Xtratalk 300",
		price: "300.00",
		allowance: "Xtratalk 300",
		product_id: "MT600",
		validity: "Xtratalk 300",
	},
	{
		network: "MTN",
		category: "Xtratalk 500",
		price: "500.00",
		allowance: "Xtratalk 500",
		product_id: "MT601",
		validity: "Xtratalk 500",
	},
	{
		network: "MTN",
		category: "Xtratalk 1000",
		price: "1000.00",
		allowance: "Xtratalk 1000",
		product_id: "MT602",
		validity: "Xtratalk 1000",
	},
	{
		network: "MTN",
		category: "Xtratalk 2000",
		price: "2000.00",
		allowance: "Xtratalk 2000",
		product_id: "MT603",
		validity: "Xtratalk 2000",
	},
	{
		network: "MTN",
		category: "Xtratalk 5000",
		price: "5000.00",
		allowance: "Xtratalk 5000",
		product_id: "MT604",
		validity: "Xtratalk 5000",
	},
	{
		network: "MTN",
		category: "Xtratalk 10000",
		price: "10000.00",
		allowance: "Xtratalk 10000",
		product_id: "MT605",
		validity: "Xtratalk 10000",
	},
	{
		network: "MTN",
		category: "Xtratalk 15000",
		price: "15000.00",
		allowance: "Xtratalk 15000",
		product_id: "MT606",
		validity: "Xtratalk 15000",
	},
	{
		network: "MTN",
		category: "Xtratalk 20000",
		price: "20000.00",
		allowance: "Xtratalk 20000",
		product_id: "MT607",
		validity: "Xtratalk 20000",
	},
	{
		network: "MTN",
		category: "Xtradata 300",
		price: "300.00",
		allowance: "Xtradata 300",
		product_id: "MT609",
		validity: "Xtradata 300",
	},
	{
		network: "MTN",
		category: "Xtradata 500",
		price: "500.00",
		allowance: "Xtradata 500",
		product_id: "MT610",
		validity: "Xtradata 500",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "13500.00",
		allowance: "35GB SME",
		product_id: "MT612",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Yearly",
		price: "120000.00",
		allowance: "400GB",
		product_id: "MT700",
		validity: "365Days",
	},
	{
		network: "MTN",
		category: "Yearly",
		price: "150000.00",
		allowance: "1.5TB Yearly Broadband Plan (4G Router)",
		product_id: "MTTB",
		validity: "1 Year",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "165000.00",
		allowance: "Platinum (1.5TB FUP Six-Months Unlimited) Plan (4G",
		product_id: "MTFUP",
		validity: "6 Months",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "100000.00",
		allowance: "1TB 6-Months Broadband Plan (4G Router)",
		product_id: "MT6B",
		validity: "6 Months",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "60000.00",
		allowance: "Diamond (550GB FUP Monthly Unlimited) (4G Router)",
		product_id: "MT6FU",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "45000.00",
		allowance: "Gold (400GB FUP Monthly Unlimited) (4G Router)",
		product_id: "MT4FU",
		validity: "6 Months",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "45000.00",
		allowance: "400GB 3-Months Broadband Plan (4G Router)",
		product_id: "MT45F",
		validity: "3 Months",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "36000.00",
		allowance: "300GB 2-Months Broadband Plan (4G Router)",
		product_id: "MT2FU",
		validity: "2 Months",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "30000.00",
		allowance: "Ruby (300GB FUP Monthly Unlimited) Plan (4G Router",
		product_id: "MTRUB",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "25000.00",
		allowance: "200GB Monthly Broadband Plan (4G Router)",
		product_id: "MTBR1",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "25000.00",
		allowance: "200GB Monthly HyNetFlex Plan",
		product_id: "MT200",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "20000.00",
		allowance: "Silver (150GB FUP Monthly Unlimited) Plan (4G Rout",
		product_id: "MT2GB",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "18000.00",
		allowance: "100GB Monthly Broadband Plan (4G Router)",
		product_id: "MT100",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "11000.00",
		allowance: "45GB Monthly Broadband Plan (4G Router)",
		product_id: "MT110",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "8000.00",
		allowance: "30GB Monthly Broadband Plan (4G Router)",
		product_id: "MQR1",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "5000.00",
		allowance: "Marble (30GB FUP Weekly Unlimited) Plan (4G Router",
		product_id: "MTW10",
		validity: "1 Week",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "2000.00",
		allowance: "4GB+2GB YouTube Night+200MB YouTube Music + 10mins",
		product_id: "MB5B",
		validity: "30 Days",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "2000.00",
		allowance: "7GB",
		product_id: "MT08B",
		validity: "7 Days",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "350.00",
		allowance: "1GB Daily Plan + 3mins.",
		product_id: "MT04B",
		validity: "1 day",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "600.00",
		allowance: "2.5GB 2-Day Plan",
		product_id: "MN8B",
		validity: "2-Day Plan",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "1500.00",
		allowance: "5GB",
		product_id: "MM7B",
		validity: "7 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1000.00",
		allowance: "1.2GB Monthly Plan + FREE 2GB for YouTube and 200M",
		product_id: "MTB08",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "5500.00",
		allowance: "20GB+2GB YouTube Night+300MB YouTube Music + 25min",
		product_id: "MD1B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "300.00",
		allowance: "Xtratalk 300",
		product_id: "MTB60",
		validity: "Xtratalk 300",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "3500.00",
		allowance: "10GB+2GB YouTube Night+300MB YouTube Music + 20min",
		product_id: "MM9B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "22000.00",
		allowance: "120GB Monthly Plan + 80mins.",
		product_id: "MB1B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "6500.00",
		allowance: "25GB+2GB YouTube Night + 25mins.",
		product_id: "MM5B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Daily",
		price: "800.00",
		allowance: "3GB",
		product_id: "MT33B",
		validity: "2 Days",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "11000.00",
		allowance: "40GB Monthly Plan + 40mins.",
		product_id: "MD2B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "16000.00",
		allowance: "75GB + 40mins",
		product_id: "MD3B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1200.00",
		allowance: "1.5GB+2.4GB YouTube Night+3hr-200MB-YouTube Weekly",
		product_id: "MT25B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "1600.00",
		allowance: "3GB+2GB YouTube Night+200MB YouTube Music + 5mins.",
		product_id: "MN3B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Weekly",
		price: "600.00",
		allowance: "1GB Weekly Plan + FREE 1GB for YouTube and 100MB f",
		product_id: "MT05B",
		validity: "1 Week",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "3000.00",
		allowance: "6GB+2GB YouTube Night+200MB YouTube Music + 15mins",
		product_id: "MM8B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "4000.00",
		allowance: "12GB+2GB YouTube Night + 25mins.",
		product_id: "MD4B",
		validity: "1 Month",
	},
	{
		network: "MTN",
		category: "Monthly",
		price: "5500.00",
		allowance: "20GB+2GB YouTube Night+300MB YouTube Music + 25min",
		product_id: "MT6BB",
		validity: "1 Month",
	},
];